name: 2b-test-cases
on: push
jobs:
     run-tastes:
         runs-on: ubuntu-latest
         steps:
             - name: checkout
               uses: actions/checkout@v4
             - name: install dependancies
               uses: actions/setup-python@v2
               with:
                 python-version: '3.4x'
             - name: install libiraries
               run: pip insatall -r requirments.txt
             - name: run test
               run: pyrhon -m unittrst test.py      
     deploy:
         needs: run-tests   
         runs-on: ubuntu-latest
         steps:
             - name: checkout
               uses: actions/checkout@v4 
             - name: deploy-done
               run: echo "Deployed Succsseful"
